### ISSUE TITLE
TaraClient: Store bridgeRoot for all the epochs, but not only the latest one

### ISSUE THREAD

**Issue by kstdl** [Taraxa-project/bridge#34]
Right now ew are storing only the most recent finalized block. So if we will submit a batch with a few different bridgeRoots we will loose all but the latest. So we need something like additional mapping(like epoch=>bridgeRoot) for it. Also `getFinalizedBridgeRoot` should accept an epoch argument and return a value from the map that I mentioned above 
Please check EthClient for the same issue, probably we will have something like this there also

**Comment by VargaElod23** [comment]
@kstdl There is no such thing as an epoch on the EthBridge side. Should that also be added?
